import puppeteer from 'puppeteer-core'
const [,, base='http://127.0.0.1:4180/', W='844', H='390', mobile='1', prefix='previews/'] = process.argv
const sleep = ms => new Promise(r => setTimeout(r, ms))
const b = await puppeteer.launch({ executablePath: '/usr/bin/google-chrome', headless: 'new', args: ['--no-sandbox','--autoplay-policy=no-user-gesture-required','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader','--ignore-gpu-blocklist'] })
const p = await b.newPage()
if (mobile === '1') await p.setUserAgent('Mozilla/5.0 (Linux; Android 13; Pixel 6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Mobile Safari/537.36')
await p.setViewport({ width: +W, height: +H, deviceScaleFactor: 1, isMobile: mobile === '1', hasTouch: mobile === '1', isLandscape: true })
if (process.env.PLATO) await p.evaluateOnNewDocument(pl => { try { const o = JSON.parse(localStorage.getItem('ac3d_opts') || '{}'); o.plato = pl; localStorage.setItem('ac3d_opts', JSON.stringify(o)) } catch { } }, process.env.PLATO)
p.on('pageerror', e => console.log('PAGEERROR', e.message))
p.on('console', m => { if (m.type()==='error') console.log('CONSOLE', m.text()) })
const log = (...a) => console.log(new Date().toISOString().slice(11,19), ...a)
const shot = async n => { await p.screenshot({ path: prefix + n }); log('shot', n) }
const until = async (fn, ms = 60000, arg) => { const t = Date.now(); while (Date.now() - t < ms) { if (await p.evaluate(fn, arg).catch(() => false)) return true; await sleep(150) } throw new Error('timeout ' + fn) }
await p.goto(base + '?nosw&screen=play', { waitUntil: 'load' })
await until(() => !document.getElementById('menu').classList.contains('hidden') && document.querySelector('.mbtn'))
await sleep(2500); await shot('01c-jugar-flow.png')
log('fps', await p.evaluate(() => window.__eng.fps))
// --- Programa completo
await p.click('.mbtn.gold')
await sleep(2600); await shot('08-cabecera-logo.png')
await sleep(5200); await shot('09-cabecera-plato.png')
await p.click('#btnSkip'); log('saltar')
await until(() => [...document.querySelectorAll('#actions button')].some(b => b.textContent.includes('centro')), 20000)
await sleep(800); await shot('10-bienvenida-camina.png')
// caminar con el teclado (W) 1,2 s
const z0 = await p.evaluate(() => window.__eng.player.root.position.z)
await p.keyboard.down('KeyW'); await sleep(1200); await p.keyboard.up('KeyW')
const z1 = await p.evaluate(() => window.__eng.player.root.position.z); log('walk z', z0.toFixed(2), '->', z1.toFixed(2))
await shot('11-caminando.png')
await p.evaluate(() => [...document.querySelectorAll('#actions button')].find(b => b.textContent.includes('centro')).click())
await until(() => document.querySelector('img.huella') && getComputedStyle(document.querySelector('img.huella')).display !== 'none', 40000)
await sleep(900); await shot('04-huellas.png')
await p.evaluate(() => document.querySelectorAll('img.huella')[2].click())
await until(() => window.__panel.active, 30000)
await sleep(1200)
const miss = await p.evaluate(() => window.__panel.q.missing.join('')); log('faltan', miss)
await p.keyboard.type(miss.slice(0, 1)); await sleep(500)
await shot('05-prueba.png')
// una letra mal para probar el error
await p.keyboard.type(miss.slice(1)); 
await until(() => window.__eng.studio.holes.some((h, i) => i > 0 && h.target === 1), 30000)
await sleep(250); await shot('06-caida.png')
await until(() => { const e = [...document.querySelectorAll('#stageBox img')].find(i => i.src && getComputedStyle(i).display !== 'none' && i.classList.contains('click')); return !!e }, 30000)
await sleep(1200); await shot('12-moneda.png')
await p.evaluate(() => [...document.querySelectorAll('#stageBox img.click')].filter(i => getComputedStyle(i).display !== 'none')[0].click())
await sleep(3500); await shot('13-moneda-abierta.png')
await sleep(4500); await shot('14-marcador.png')
await until(() => document.querySelector('img.huella') && getComputedStyle(document.querySelector('img.huella')).display !== 'none', 40000)
log('ronda 2 OK')
// --- Entrenamiento
await p.goto(base + '?nosw&mode=entrenamiento&sub=pruebas', { waitUntil: 'load' })
await until(() => window.__panel?.active, 30000); await sleep(1500)
await p.keyboard.type('ZZ'); await sleep(250)
await shot('07-entrenamiento.png')
await b.close()
