// Pruebas v1.2: audio propio (Opciones), duelos contra el bot con dos relojes, PASAR (duelo y Juego Final), caídas.
// Uso: node test/v12.mjs <parte: audio|final|pierde|entreno> [base]
import puppeteer from 'puppeteer-core'
const [,, part = 'audio', base = 'http://127.0.0.1:4180/', W = '844', H = '390'] = process.argv
const P = 'previews/'
const sleep = ms => new Promise(r => setTimeout(r, ms))
const b = await puppeteer.launch({ executablePath: '/usr/bin/google-chrome', headless: 'new', args: ['--no-sandbox', '--autoplay-policy=no-user-gesture-required', '--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader', '--ignore-gpu-blocklist'] })
const p = await b.newPage()
await p.setUserAgent('Mozilla/5.0 (Linux; Android 13; Pixel 6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Mobile Safari/537.36')
await p.setViewport({ width: +W, height: +H, deviceScaleFactor: 1, isMobile: true, hasTouch: true, isLandscape: true })
const errors = []
p.on('pageerror', e => { errors.push(e.message); console.log('PAGEERROR', e.message) })
p.on('console', m => { if (m.type() === 'error' && !/favicon|404/.test(m.text())) console.log('CONSOLE', m.text()) })
const t0 = Date.now(); const log = (...a) => console.log(((Date.now() - t0) / 1000).toFixed(1).padStart(6), ...a)
const shot = async n => { await p.screenshot({ path: P + n }); log('📸', n) }
const until = async (fn, ms = 60000, arg) => { const t = Date.now(); while (Date.now() - t < ms) { if (await p.evaluate(fn, arg).catch(() => false)) return true; await sleep(120) } throw new Error('timeout ' + fn.toString().slice(0, 140)) }
const ev = (fn, arg) => p.evaluate(fn, arg)
let fails = 0; const check = (ok, msg) => { console.log((ok ? '  ✅ ' : '  ❌ ') + msg); if (!ok) fails++ }
const answer = async () => { const m = await ev(() => window.__panel.q.missing.join('')); await p.keyboard.type(m) }
const musicName = () => ev(() => window.__audio.musicName())
const goCenter = async () => {
  await until(() => [...document.querySelectorAll('#actions button')].some(b => b.textContent.includes('centro')), 60000)
  await ev(() => [...document.querySelectorAll('#actions button')].find(b => b.textContent.includes('centro')).click())
}
const pickHuella = async (i = 0) => {
  await until(() => document.querySelector('img.huella') && getComputedStyle(document.querySelector('img.huella')).display !== 'none', 60000)
  await sleep(700); await ev(i => [...document.querySelectorAll('img.huella')].filter(x => x.classList.contains('click'))[i].click(), i)
}
const duelState = () => ev(() => window.__duel ? { turn: window.__duel.turn, me: +window.__duel.clocks.me.toFixed(2), bot: +window.__duel.clocks.bot.toFixed(2), running: window.__duel.running, log: window.__duel.log.join(','), opp: window.__duel.opp } : null)
const myTurnActive = () => until(() => window.__duel && window.__duel.turn === 'me' && window.__panel.active && document.getElementById('btnPasar'), 60000)
const barVisible = () => ev(() => !!document.getElementById('duelBar'))

if (part === 'audio') {
  // ---------- A) Opciones › Música de la cabecera
  await p.goto(base + '?nosw&screen=options', { waitUntil: 'load' })
  await until(() => document.getElementById('optCustom'))
  await sleep(1500); await shot('31-opciones-audio.png')
  check(await ev(() => document.getElementById('optCustom').textContent.includes('El audio se queda solo en este dispositivo; no se sube ni se comparte.')), 'nota de privacidad visible')
  check(await ev(() => document.getElementById('customFile').accept === 'audio/*'), 'input file accept=audio/*')
  check(await ev(() => document.getElementById('btnProbarAudio').disabled && document.getElementById('btnQuitarAudio').disabled), 'sin audio: Probar/Quitar desactivados')
  const inp = await p.$('#customFile'); await inp.uploadFile('/tmp/mi-sintonia-prueba.mp3')
  await until(() => document.querySelector('#optCustom .oname b')?.textContent === 'mi-sintonia-prueba.mp3', 20000)
  await sleep(800); await shot('31b-opciones-audio-elegido.png')
  const stored = await ev(() => new Promise(r => { const q = indexedDB.open('ac3d_local'); q.onsuccess = () => { const g = q.result.transaction('audio').objectStore('audio').get('cabecera'); g.onsuccess = () => r(g.result ? { name: g.result.name, size: g.result.blob.size } : null) } }))
  check(stored && stored.name === 'mi-sintonia-prueba.mp3' && stored.size > 100000, 'guardado en IndexedDB del dispositivo: ' + JSON.stringify(stored))
  await ev(() => document.getElementById('btnProbarAudio').click()); await sleep(700)
  check(await musicName() === 'custom:cabecera', 'Probar reproduce el audio propio')
  await ev(() => document.getElementById('btnProbarAudio').click()); await sleep(1500)
  check(await musicName() === 'Trilha', 'Parar vuelve a la música del menú')
  // persistencia tras recargar
  await p.goto(base + '?nosw&screen=play', { waitUntil: 'load' })
  await until(() => window.__custom && window.__custom.customInfo()?.name === 'mi-sintonia-prueba.mp3', 20000)
  check(true, 'el audio sigue guardado tras recargar')
  // ---------- Programa completo con audio propio
  await ev(() => { window.__botForce = 'win'; window.__botClock = 20 })
  await ev(() => { window.__pruebaForce = 'clasico'; window.__noEleccion = true; localStorage.setItem('ac3d_concursantes', JSON.stringify({ presentaciones: false, eleccion: false })); window.__cons.reload() })
  await ev(() => { void window.__startMode('programa') })
  await until(() => window.__audio.musicName() === 'custom:cabecera', 15000)
  check(true, 'la cabecera suena con el audio propio')
  const mt = () => ev(() => window.__audio.musicTime('custom:cabecera'))
  while ((await mt()) < 5.0) await sleep(50)
  await shot('32-cabecera-logo.png')
  while ((await mt()) < 9.0) await sleep(100)
  await shot('32b-cabecera-dron-audio-propio.png')
  await goCenter(); log('bienvenida')
  check(await musicName() !== 'custom:cabecera', 'el audio propio se funde al terminar la cabecera (ahora: ' + await musicName() + ')')
  check(!(await barVisible()), 'relojes del duelo ocultos fuera del duelo')
  // ---------- Duelo 1: el bot contesta, PASAR con comodín ×2, PASAR sin comodín, el bot cae
  await pickHuella(2); await sleep(600)
  check(!(await ev(() => document.querySelector('img.huella') && [...document.querySelectorAll('img.huella')].some(i => getComputedStyle(i).display !== 'none' && i.style.opacity !== '0'))), 'rueda ELIGE oculta tras elegir')
  await until(() => window.__duel && window.__duel.turn === 'bot' && window.__duel.running, 30000)
  check(await barVisible(), 'relojes de los dos visibles en el duelo')
  await until(() => [...document.querySelectorAll('.pslots .slot.bot')].some(s => s.textContent), 30000)
  await sleep(150); await shot('33-duelo-bot-responde.png')
  let d = await duelState(); log('duelo', JSON.stringify(d))
  check(d.me === 30, 'mientras juega el bot, tu reloj no corre (' + d.me + ')')
  await myTurnActive(); await sleep(1500)
  await shot('34-duelo-dos-relojes-pasar.png')
  d = await duelState(); const botAfter1 = d.bot
  check(d.log.includes('bot-ok'), 'el bot ha acertado su pregunta')
  check(d.bot < 20 && d.me < 30, `dos relojes independientes: tú ${d.me}, bot ${d.bot}`)
  const v0 = await ev(() => document.querySelector('#vidas img')?.src || '')
  await ev(() => document.getElementById('btnPasar').click()); log('PASAR (comodín 1)')
  await until(() => window.__duel.turn === 'bot', 10000)
  d = await duelState(); check(d.log.includes('me-pasa-comodin'), 'PASAR con comodín: la pregunta pasa al oponente')
  await sleep(1200); check((await duelState()).bot < botAfter1, 'ahora corre el reloj del bot')
  await myTurnActive(); await sleep(400)
  await ev(() => document.getElementById('btnPasar').click()); log('PASAR (comodín 2)')
  await until(() => window.__duel.turn === 'bot', 10000)
  await myTurnActive(); await sleep(600)
  check(await ev(() => !document.getElementById('btnPasar').innerHTML.includes('comodín')), 'sin comodines el botón es PASAR a secas')
  const me1 = (await duelState()).me
  await ev(() => document.getElementById('btnPasar').click()); log('PASAR (sin comodín)')
  await sleep(1500); d = await duelState()
  check(d.turn === 'me' && d.log.endsWith('me-pasa'), 'PASAR sin comodín: sigues tú con otra pregunta')
  check(d.me < me1 - 1.0, `el reloj sigue corriendo al pasar (${me1} → ${d.me})`)
  await myTurnActive(); await sleep(500)
  await ev(() => { window.__botForce = 'fail' })
  await answer(); log('respondo')
  await until(() => window.__duel.turn === 'bot' && [...document.querySelectorAll('.pslots .slot.think')].length, 15000)
  await sleep(600); await shot('33b-duelo-bot-pensando.png')
  const opp = (await duelState()).opp
  await until(o => window.__eng.studio.holes[o].target === 1, 60000, opp)
  const y0 = await ev(o => window.__eng.opps[o - 1].root.position.y, opp)
  await until(([o, y]) => window.__eng.opps[o - 1].root.position.y < y - 0.35, 20000, [opp, y0])
  await shot('35-bot-cae.png'); await until(([o, y]) => !window.__eng.opps[o - 1].root.visible || window.__eng.opps[o - 1].root.position.y < y - 1.6, 20000, [opp, y0]).catch(() => { }); await shot('35b-bot-cae-trampilla.png')
  d = await duelState(); check(d.log.includes('bot-tiempo'), 'al bot se le acaba el tiempo y cae por su trampilla')
  await until(() => [...document.querySelectorAll('#stageBox img.click')].some(i => getComputedStyle(i).display !== 'none'), 40000)
  check(true, 'tras la caída del bot sigue el programa (moneda)')
  await sleep(1000); check(!(await barVisible()), 'relojes del duelo ocultos tras el duelo')
} else if (part === 'final') {
  // ---------- Juego Final con PASAR (sin audio propio: música del .sb3)
  await p.goto(base + '?nosw&screen=play&theme=primetime', { waitUntil: 'load' })
  await until(() => window.__eng && document.querySelector('.mbtn.gold'))
  await ev(() => { window.__testRodadas = 7; window.__botForce = 'fail'; window.__botClock = 4 })
  await ev(() => { window.__pruebaForce = 'clasico'; window.__noEleccion = true; localStorage.setItem('ac3d_concursantes', JSON.stringify({ presentaciones: false, eleccion: false })); window.__cons.reload() })
  await ev(() => { void window.__startMode('programa') })
  await until(() => window.__audio.musicName() != null, 15000)
  check(await musicName() === 'Trilha', 'sin audio propio la cabecera usa la música del minijuego (Trilha), no la sintonía descartada')
  await sleep(2500); await p.click('#btnSkip')
  await goCenter(); await pickHuella(0)
  const opp = await (async () => { await until(() => window.__duel, 30000); return (await duelState()).opp })()
  await until(o => window.__eng.studio.holes[o].target === 1, 60000, opp); check(true, 'bot del duelo 8 cae')
  await until(() => window.__st.els.get('Moeda1') && window.__st.els.get('Moeda1').style.display !== 'none', 40000); await sleep(800)
  await ev(() => __st.els.get('Moeda2').click())
  await until(() => window.__st.els.get('BotãoMenu4') && window.__st.els.get('BotãoMenu4').style.display !== 'none', 60000); await sleep(800)
  await ev(() => __st.els.get('BotãoMenu4').click())
  await until(() => window.__panel.active && document.getElementById('btnPasar'), 60000)
  check(!(await barVisible()), 'en el Juego Final no aparecen los relojes del duelo')
  await sleep(3500)
  const q1 = await ev(() => window.__panel.q.id); const tA = await ev(() => document.querySelector('#panelBox').innerText)
  await shot('36-juego-final-pasar.png')
  const c0 = await ev(() => [1, 2, 3, 4].map(i => window.__panel.st.els.get('d' + i)?.src.split('/').pop()).join('|'))
  await ev(() => document.getElementById('btnPasar').click()); log('PASAR en el Juego Final')
  const c1 = await ev(() => window.__panel.q.id); await until(q => window.__panel.active && window.__panel.q.id !== q, 20000, q1).catch(() => { }); await sleep(300)
  const q2 = await ev(() => window.__panel.q.id)
  check(q1 !== q2, `PASAR salta a la siguiente pregunta (${q1} → ${q2})`)
  for (let i = 0; i < 10; i++) {
    await until(() => window.__panel.active, 40000); await sleep(350)
    await answer(); log('final', i + 1); await sleep(1100)
  }
  await until(() => document.getElementById('credits') && !document.getElementById('credits').classList.contains('hidden'), 60000)
  check(await musicName() === 'Trilha', 'despedida con la música del minijuego (sin audio propio)')
  await until(() => [...document.querySelectorAll('#actions button')].length > 0, 60000)
  check(await ev(() => document.getElementById('scorebox')?.textContent.includes('ganado')), 'Juego Final ganado tras usar PASAR: ' + await ev(() => document.getElementById('scorebox')?.textContent))
} else if (part === 'pierde') {
  // ---------- El concursante pierde (se le acaba su reloj)
  await p.goto(base + '?nosw&screen=play', { waitUntil: 'load' })
  await until(() => window.__eng && document.querySelector('.mbtn.gold'))
  await ev(() => { window.__meFirst = 1; window.__duelClock = 6 })
  await ev(() => { window.__pruebaForce = 'clasico'; window.__noEleccion = true; localStorage.setItem('ac3d_concursantes', JSON.stringify({ presentaciones: false, eleccion: false })); window.__cons.reload() })
  await ev(() => { void window.__startMode('programa') })
  await sleep(2500); await p.click('#btnSkip')
  await goCenter(); await pickHuella(4)
  await myTurnActive(); await sleep(2500); await shot('37-duelo-tu-turno.png')
  await until(() => window.__eng.studio.holes[0].target === 1, 60000); await sleep(400); await shot('38-concursante-cae.png')
  check((await duelState()).log.includes('me-tiempo'), 'si se te acaba el reloj, caes tú')
  await until(() => [...document.querySelectorAll('#actions button')].length > 0, 90000)
  check(await ev(() => document.getElementById('scorebox')?.textContent.includes('caído')), 'final de partida perdida: ' + await ev(() => document.getElementById('scorebox')?.textContent))
} else if (part === 'entreno') {
  // ---------- Entrenamiento: duelo contra un oponente y PASAR en pruebas
  await p.goto(base + '?nosw&screen=train', { waitUntil: 'load' })
  await until(() => document.querySelector('.mbtn.gold')); await sleep(1200); await shot('39-entrenamiento-menu.png')
  await p.goto(base + '?nosw&mode=entrenamiento&sub=duelo', { waitUntil: 'load' })
  await until(() => window.__duel && window.__duel.running, 40000)
  await ev(() => { window.__botForce = 'fail' }); await myTurnActive().catch(() => { })
  check(await barVisible(), 'entrenamiento de duelo con los dos relojes')
  await p.goto(base + '?nosw&mode=entrenamiento&sub=pruebas', { waitUntil: 'load' })
  await until(() => window.__panel?.active && document.getElementById('btnPasar'), 30000)
  const q1 = await ev(() => window.__panel.q.id)
  await ev(() => document.getElementById('btnPasar').click())
  await until(q => window.__panel.active && window.__panel.q.id !== q, 20000, q1); check(true, 'PASAR en el entrenamiento de pruebas')
  // quitar el audio propio (estado sin audio)
  await p.goto(base + '?nosw&screen=options', { waitUntil: 'load' })
  await until(() => document.getElementById('optCustom'))
  const inp = await p.$('#customFile'); await inp.uploadFile('/tmp/mi-sintonia-prueba.mp3')
  await until(() => !document.getElementById('btnQuitarAudio').disabled, 20000)
  await ev(() => document.getElementById('btnQuitarAudio').click())
  await until(() => document.getElementById('btnQuitarAudio')?.disabled, 10000)
  const left = await ev(() => new Promise(r => { const q = indexedDB.open('ac3d_local'); q.onsuccess = () => { const g = q.result.transaction('audio').objectStore('audio').get('cabecera'); g.onsuccess = () => r(g.result || null) } }))
  check(left === null, 'Quitar borra el audio del dispositivo')
}
check(errors.length === 0, 'sin errores de JavaScript')
console.log(fails ? `FALLOS: ${fails}` : 'TODO OK', `(${part})`)
await b.close(); process.exit(fails ? 1 : 0)
