// v1.6: pruebas «¡Vaya lío!» y «Palabra gallina» con canción del jugador (entrenamiento + Opciones)
import puppeteer from 'puppeteer-core'
const [,, base = 'http://127.0.0.1:4190/', prefix = 'previews/plato-privado/final/'] = process.argv
const PL = process.env.PLATO || 'virtual'
const sleep = ms => new Promise(r => setTimeout(r, ms))
const b = await puppeteer.launch({ executablePath: '/usr/bin/google-chrome', headless: 'new', args: ['--no-sandbox', '--autoplay-policy=no-user-gesture-required', '--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader', '--ignore-gpu-blocklist'] })
const p = await b.newPage(); await p.setViewport({ width: 1024, height: 576 })
let fails = 0; const check = (ok, m) => { console.log((ok ? '  ✅ ' : '  ❌ ') + m); if (!ok) fails++ }
p.on('pageerror', e => console.log('PAGEERROR', e.message))
const until = async (fn, ms = 60000, ...a) => { const t = Date.now(); while (Date.now() - t < ms) { if (await p.evaluate(fn, ...a).catch(() => false)) return true; await sleep(150) } throw new Error('timeout ' + fn) }
const ev = (fn, ...a) => p.evaluate(fn, ...a)
await p.goto(base + '?nosw', { waitUntil: 'load' })
await ev(pl => localStorage.setItem('ac3d_opts', JSON.stringify({ ...JSON.parse(localStorage.getItem('ac3d_opts') || '{}'), plato: pl })), PL)
// ---------------- VAYA LÍO
await p.goto(base + '?nosw&screen=train', { waitUntil: 'load' })
await until(() => !!(window.__eng && window.__eng.studio))
await ev(() => { window.__meFirst = true; window.__trOpp = 3; window.__botForce = 'win'; void window.__startMode('entrenamiento', 'vayalio') })
await until(() => window.__duel && window.__duel.turn === 'me' && document.querySelector('.ptxt.vlio') && !window.__duel.leyendo, 90000)
const q = await ev(() => ({ word: window.__panel.q.word, exact: window.__panel.q.exact, text: window.__panel.q.text }))
console.log('vaya lío:', q)
check(q.exact && q.word && [...q.word.normalize('NFD').replace(/[\u0300-\u036f]/g, '')].sort().join('') === [...q.exact].sort().join(''), 'las casillas son un anagrama de la respuesta')
check(await ev(() => !!window.__eng.split && !!document.getElementById('splitUi')), 'pantalla partida con los dos duelistas')
await sleep(800); await p.screenshot({ path: prefix + 'vaya-lio.png' }); console.log('📸 vaya-lio.png')
// con las letras en otro orden NO vale
await p.keyboard.type(q.word.normalize('NFD').replace(/[\u0300-\u036f]/g, '')); await sleep(600)
check(await ev(() => window.__duel.turn === 'me' && !window.__duel.log.includes('me-ok')), 'escribir las letras revueltas no cuenta')
await p.keyboard.type(q.exact)
await until(() => window.__duel.log.includes('me-ok'), 8000)
check(true, 'la respuesta bien ordenada se acepta')
await sleep(300); await p.screenshot({ path: prefix + 'vaya-lio-acierto.png' })
check(await ev(() => window.__lector.log.some(l => l.startsWith('lee:'))), 'el presentador lee la definición (lectura 1.5)')
// ---------------- PALABRA GALLINA: Opciones › mis canciones
await p.goto(base + '?nosw&screen=options', { waitUntil: 'load' })
await until(() => document.getElementById('btnGallina'))
await ev(() => document.getElementById('btnGallina').click())
await until(() => document.getElementById('btnAddCancion'))
await ev(() => document.getElementById('btnAddCancion').click())
await until(() => document.getElementById('gallinaEditor'))
const fi = await p.$('#gInp'); await fi.uploadFile('test/fixtures/cancion-prueba.mp3')
await until(() => document.getElementById('gFileName').textContent.includes('cancion-prueba'))
const LETRA = 'Bajo las luces del plató\nel reloj empieza a correr\nsi me caigo me levanto\ny vuelvo a intentarlo otra vez'
await ev(L => { const t = document.getElementById('gTitulo'); t.value = 'La canción del plató (prueba)'; const a = document.getElementById('gLetra'); a.value = L; const i = L.indexOf('vuelvo a intentarlo'); a.focus(); a.setSelectionRange(i + 2, i + 17); document.getElementById('gMarcar').click(); document.getElementById('gCorte').value = '12'; document.getElementById('gDesde').value = '4' }, LETRA)
check(await ev(() => document.getElementById('gFrag').textContent.includes('vuelvo a intentarlo')), 'el trozo marcado se ajusta a palabras completas')
await ev(() => document.getElementById('gPrev').click())
await until(() => !document.getElementById('gPrevBox').classList.contains('escuchando') && document.querySelector('#gPrevBox .gq'), 20000)
await ev(() => document.getElementById('gallinaEditor').scrollIntoView({ block: 'end' })); await sleep(400)
await p.screenshot({ path: prefix + 'gallina-opciones.png' }); console.log('📸 gallina-opciones.png')
await ev(() => document.getElementById('gSave').click())
await until(() => document.querySelector('#gallinaLista .gcan'), 10000)
check(await ev(() => window.__gallinaApi.canciones().length === 1), 'la canción se guarda (solo en este dispositivo)')
await p.screenshot({ path: prefix + 'gallina-lista.png' })
// ---------------- PALABRA GALLINA en juego (entrenamiento)
await p.goto(base + '?nosw&screen=train', { waitUntil: 'load' })
await until(() => !!(window.__eng && window.__eng.studio) && window.__gallinaApi.canciones().length === 1)
await ev(() => { void window.__startMode('entrenamiento', 'gallina') })
await until(() => window.__gallina && window.__gallina.estado === 'sonando', 60000)
check(await ev(() => document.querySelector('.ptxt.gall.escuchando') != null), 'mientras suena la canción, la frase está tapada')
await p.screenshot({ path: prefix + 'gallina-escuchando.png' })
await until(() => window.__gallina.estado === 'cortada', 20000)
check(await ev(() => window.__gallina.t >= 11.8 && window.__gallina.t < 12.5), 'la música se corta en el segundo marcado')
await sleep(900); await p.screenshot({ path: prefix + 'gallina-juego.png' }); console.log('📸 gallina-juego.png')
const g = await ev(() => ({ text: window.__panel.q.text, word: window.__panel.q.word, miss: window.__panel.q.missing }))
console.log('gallina:', g)
check(g.text.includes('____') && g.word === 'VUELVO A INTENTARLO', 'frase con el hueco y casillas del fragmento')
await p.keyboard.type(g.miss.join('')); await sleep(1500)
check(await ev(() => document.querySelector('.pboxes.reveal') != null), 'completar la letra la da por buena')
await b.close(); console.log(fails ? `❌ ${fails} fallos` : '✅ todo bien'); process.exit(fails ? 1 : 0)
