// Bancos de preguntas originales para las pruebas de v1.3 (redactadas para este juego).
// ENTRE TRES: [pregunta, [3 opciones], índice correcto]. ADIVINA: categoría, 5 pistas (de difícil a fácil) y respuesta.
// CENTRAL (elección del central): pregunta y respuesta de una palabra.
export type E3 = [string, [string, string, string], number];
export const ENTRE_TRES: E3[] = [
  ['¿Cuál es el planeta más grande del sistema solar?', ['Júpiter', 'Saturno', 'Neptuno'], 0],
  ['¿Cuál es la última palabra por orden alfabético?', ['Mesa', 'Mapa', 'Mono'], 2],
  ['¿Cuál es la primera palabra por orden alfabético?', ['Perro', 'Pato', 'Pez'], 1],
  ['¿Cuántos lados tiene un hexágono?', ['5', '6', '8'], 1],
  ['¿Qué mar baña la costa de Valencia?', ['Cantábrico', 'Báltico', 'Mediterráneo'], 2],
  ['¿En qué país está Machu Picchu?', ['Perú', 'Bolivia', 'México'], 0],
  ['¿Cuál es el símbolo químico del oro?', ['Ag', 'Au', 'Or'], 1],
  ['¿Cuál es el río más largo de la península ibérica?', ['Ebro', 'Duero', 'Tajo'], 2],
  ['¿Quién pintó «Las meninas»?', ['Velázquez', 'Goya', 'Murillo'], 0],
  ['¿Cuántos jugadores de un equipo de baloncesto están en la pista a la vez?', ['6', '5', '7'], 1],
  ['¿Cuál es el animal terrestre más rápido?', ['León', 'Caballo', 'Guepardo'], 2],
  ['¿Cuál es la capital de Australia?', ['Canberra', 'Sídney', 'Melbourne'], 0],
  ['¿En qué año llegó Colón a América?', ['1452', '1492', '1512'], 1],
  ['¿Cuál es el hueso más largo del cuerpo humano?', ['Tibia', 'Húmero', 'Fémur'], 2],
  ['¿Qué gas absorben las plantas para hacer la fotosíntesis?', ['Dióxido de carbono', 'Helio', 'Nitrógeno'], 0],
  ['¿Quién escribió «Don Quijote de la Mancha»?', ['Lope de Vega', 'Cervantes', 'Quevedo'], 1],
  ['¿Cuál de estos animales es un mamífero?', ['Tiburón', 'Atún', 'Delfín'], 2],
  ['¿Cuántos minutos hay en hora y media?', ['90', '80', '100'], 0],
  ['¿Cuál es la capital de Canadá?', ['Toronto', 'Ottawa', 'Montreal'], 1],
  ['¿Qué instrumento tiene normalmente 88 teclas?', ['Acordeón', 'Arpa', 'Piano'], 2],
  ['¿Cuál es la montaña más alta de España?', ['Teide', 'Mulhacén', 'Aneto'], 0],
  ['¿Qué país tiene forma de bota?', ['Grecia', 'Italia', 'Portugal'], 1],
  ['¿Cuánto es 7 × 8?', ['54', '64', '56'], 2],
  ['¿Cuál es la moneda de Japón?', ['Yen', 'Won', 'Yuan'], 0],
  ['¿En qué continente está Egipto?', ['Asia', 'África', 'Europa'], 1],
  ['¿Qué color sale al mezclar azul y amarillo?', ['Morado', 'Naranja', 'Verde'], 2],
  ['¿Cuántas patas tiene una araña?', ['8', '6', '10'], 0],
  ['¿Qué planeta es conocido como el planeta rojo?', ['Venus', 'Marte', 'Mercurio'], 1],
  ['¿Cuál es la última palabra por orden alfabético?', ['Sol', 'Sal', 'Sur'], 2],
  ['¿Cuál de estas palabras es aguda?', ['Canción', 'Árbol', 'Lápiz'], 0],
  ['¿Cuál de estas palabras es esdrújula?', ['Camión', 'Música', 'Fácil'], 1],
  ['¿Qué ciudad es conocida como la Ciudad Condal?', ['Sevilla', 'Bilbao', 'Barcelona'], 2],
  ['¿En qué ciudad está la Alhambra?', ['Granada', 'Córdoba', 'Toledo'], 0],
  ['¿Qué metal es líquido a temperatura ambiente?', ['Plomo', 'Mercurio', 'Estaño'], 1],
  ['¿Cuántos años tiene un siglo?', ['10', '1000', '100'], 2],
  ['¿Qué científico formuló la teoría de la relatividad?', ['Einstein', 'Newton', 'Darwin'], 0],
  ['¿Cuál es el océano más grande?', ['Atlántico', 'Pacífico', 'Índico'], 1],
  ['¿Qué selección ganó el Mundial de fútbol de 2010?', ['Países Bajos', 'Alemania', 'España'], 2],
  ['¿Cuántos aros tiene la bandera olímpica?', ['5', '6', '4'], 0],
  ['¿Qué órgano bombea la sangre por el cuerpo?', ['Hígado', 'Corazón', 'Pulmón'], 1],
  ['¿Cuál es la capital de Portugal?', ['Oporto', 'Coímbra', 'Lisboa'], 2],
  ['¿Cuál de estos animales es un anfibio?', ['Rana', 'Lagarto', 'Tortuga'], 0],
  ['¿Qué número romano vale 50?', ['C', 'L', 'D'], 1],
  ['¿Quién compuso «Las cuatro estaciones»?', ['Mozart', 'Bach', 'Vivaldi'], 2],
  ['¿Cuántos días tiene un año bisiesto?', ['366', '365', '364'], 0],
  ['¿Cuál es la isla más grande de las Baleares?', ['Menorca', 'Mallorca', 'Ibiza'], 1],
  ['¿Cuál es el país más grande del mundo?', ['Canadá', 'China', 'Rusia'], 2],
  ['¿En qué estado está el agua cuando es hielo?', ['Sólido', 'Líquido', 'Gaseoso'], 0],
  ['¿Cuál es la primera palabra por orden alfabético?', ['Casa', 'Cama', 'Cosa'], 1],
  ['¿Qué escritor creó a Sherlock Holmes?', ['Agatha Christie', 'Julio Verne', 'Conan Doyle'], 2],
  ['¿En qué país está la Torre Eiffel?', ['Francia', 'Bélgica', 'Suiza'], 0],
  ['¿Qué vitamina fabrica la piel con la luz del sol?', ['C', 'D', 'B12'], 1],
  ['¿Cuántos centímetros tiene un metro?', ['10', '1000', '100'], 2],
  ['¿Qué superhéroe es Peter Parker?', ['Spider-Man', 'Batman', 'Superman'], 0],
  ['¿Cuántas comunidades autónomas tiene España?', ['15', '17', '19'], 1],
  ['¿Qué planeta tiene los anillos más visibles?', ['Urano', 'Júpiter', 'Saturno'], 2],
  ['¿En qué deporte se usa un «tee»?', ['Golf', 'Tenis', 'Voleibol'], 0],
  ['¿Qué lengua tiene más hablantes nativos en el mundo?', ['Español', 'Chino mandarín', 'Inglés'], 1],
  ['¿Cuál es el desierto cálido más grande del mundo?', ['Gobi', 'Kalahari', 'Sahara'], 2],
  ['¿Cuál de estos números es primo?', ['13', '15', '21'], 0],
  ['¿Qué pintor se cortó parte de una oreja?', ['Picasso', 'Van Gogh', 'Dalí'], 1],
  ['¿En qué ciudad está el Museo del Prado?', ['Barcelona', 'Valencia', 'Madrid'], 2],
  ['¿Cuál es la última palabra por orden alfabético?', ['Luna', 'Lima', 'Lobo'], 0],
  ['¿Cuántos colores tiene el arcoíris según la tradición?', ['6', '7', '9'], 1],
  ['¿Qué animal es el símbolo de la paz?', ['Águila', 'Búho', 'Paloma'], 2],
];

export interface Adv { cat: string; pistas: [string, string, string, string, string]; r: string; alt?: string[] }
export const ADIVINA: Adv[] = [
  { cat: 'PERSONAJE', pistas: ['Sale en un cuento', 'Lleva una capa', 'Va a casa de su abuela', 'Lleva una cesta', 'Se encuentra con un lobo'], r: 'CAPERUCITA' },
  { cat: 'LUGAR', pistas: ['Es una capital europea', 'La atraviesa el río Sena', 'Allí está el museo del Louvre', 'Tiene un Arco del Triunfo muy famoso', 'Su torre más famosa es de hierro'], r: 'PARÍS' },
  { cat: 'ANIMAL', pistas: ['Vive en África', 'Es herbívora', 'Tiene manchas', 'Su lengua es muy larga', 'Tiene el cuello larguísimo'], r: 'JIRAFA' },
  { cat: 'OBJETO', pistas: ['Se abre y se cierra', 'Tiene varillas', 'Puede ser plegable', 'Se usa en días grises', 'Te protege de la lluvia'], r: 'PARAGUAS' },
  { cat: 'COMIDA', pistas: ['Es un plato español', 'Se cocina en un recipiente ancho', 'Lleva azafrán', 'Es típica de Valencia', 'Su ingrediente principal es el arroz'], r: 'PAELLA' },
  { cat: 'PERSONAJE', pistas: ['Es protagonista de una novela', 'Es de La Mancha', 'Su caballo se llama Rocinante', 'Confunde molinos con gigantes', 'Su escudero es Sancho Panza'], r: 'QUIJOTE' },
  { cat: 'LUGAR', pistas: ['Es enorme', 'Está en África', 'Hay dunas', 'Casi nunca llueve', 'Es el desierto cálido más grande del mundo'], r: 'SAHARA' },
  { cat: 'ANIMAL', pistas: ['Es un ave', 'No puede volar', 'Nada muy bien', 'Muchos viven en la Antártida', 'Parece que va de esmoquin'], r: 'PINGÜINO' },
  { cat: 'OBJETO', pistas: ['Puede ser de pulsera', 'Tiene manecillas o pantalla', 'Algunos hacen tictac', 'Hay uno famoso en la Puerta del Sol', 'Sirve para saber la hora'], r: 'RELOJ' },
  { cat: 'DEPORTE', pistas: ['Se juega con raqueta', 'Hay torneos de Grand Slam', 'Se puede jugar en tierra batida', 'Los puntos se cuentan 15, 30, 40', 'Rafa Nadal es una leyenda de este deporte'], r: 'TENIS' },
  { cat: 'PERSONAJE', pistas: ['Viste de rojo', 'Tiene barba blanca', 'Vive en el Polo Norte', 'Viaja en un trineo con renos', 'Reparte regalos en Nochebuena'], r: 'PAPÁ NOEL' },
  { cat: 'LUGAR', pistas: ['Está en Italia', 'Tiene un carnaval con máscaras', 'Hay góndolas', 'Tiene muchísimos canales', 'Su plaza más famosa es la de San Marcos'], r: 'VENECIA' },
  { cat: 'ANIMAL', pistas: ['Es un reptil', 'Mueve los ojos por separado', 'Atrapa insectos con la lengua', 'Vive en los árboles', 'Cambia de color'], r: 'CAMALEÓN' },
  { cat: 'COMIDA', pistas: ['Se fríen', 'Se hacen con masa de harina', 'Tienen forma alargada', 'Se toman en el desayuno o la merienda', 'Se mojan en chocolate'], r: 'CHURROS' },
  { cat: 'PROFESIÓN', pistas: ['Trabaja por turnos', 'Usa casco', 'Conduce un camión rojo', 'Usa mangueras', 'Apaga incendios'], r: 'BOMBERO' },
  { cat: 'LUGAR', pistas: ['No es un país', 'Se ve desde la Tierra', 'Tiene cráteres', 'Neil Armstrong caminó por ella', 'Puede estar llena, nueva o creciente'], r: 'LUNA' },
  { cat: 'PERSONAJE', pistas: ['Es de madera', 'Su padre es carpintero', 'Le aconseja un grillo', 'Quiere ser un niño de verdad', 'Le crece la nariz al mentir'], r: 'PINOCHO' },
  { cat: 'OBJETO', pistas: ['Es pequeña', 'La usan los exploradores', 'Tiene una aguja', 'Funciona con el magnetismo', 'Siempre señala el norte'], r: 'BRÚJULA' },
  { cat: 'ANIMAL', pistas: ['Es un mamífero', 'Vive en Australia', 'Tiene una cola muy fuerte', 'Se desplaza dando saltos', 'Lleva a su cría en una bolsa'], r: 'CANGURO' },
  { cat: 'LUGAR', pistas: ['Es un país', 'Está en África', 'Lo atraviesa el Nilo', 'Su capital es El Cairo', 'Tiene pirámides famosísimas'], r: 'EGIPTO' },
  { cat: 'COMIDA', pistas: ['Es un plato muy español', 'Se hace en sartén', 'Hay debate sobre si lleva cebolla', 'Lleva huevo', 'Lleva patatas'], r: 'TORTILLA' },
  { cat: 'PERSONAJE', pistas: ['Fue navegante', 'Hizo cuatro viajes', 'Sus barcos fueron la Pinta, la Niña y la Santa María', 'Le apoyaron los Reyes Católicos', 'Llegó a América en 1492'], r: 'COLÓN' },
  { cat: 'DEPORTE', pistas: ['Se suele jugar en pista cubierta', 'Cada equipo tiene cinco jugadores en pista', 'Hay tiros de tres puntos', 'Se bota el balón', 'Hay que encestar en una canasta'], r: 'BALONCESTO' },
  { cat: 'OBJETO', pistas: ['Pueden ser de sol', 'Tienen patillas', 'Tienen montura', 'Se apoyan en la nariz', 'Ayudan a ver mejor'], r: 'GAFAS' },
  { cat: 'ANIMAL', pistas: ['Es un mamífero', 'Es nocturno', 'Se orienta con ecos', 'Duerme boca abajo', 'Es el único mamífero que vuela de verdad'], r: 'MURCIÉLAGO' },
  { cat: 'LUGAR', pistas: ['Es una ciudad española', 'La atraviesa el Guadalquivir', 'Allí está la Giralda', 'Su Feria de Abril es famosa', 'Es la capital de Andalucía'], r: 'SEVILLA' },
  { cat: 'PERSONAJE', pistas: ['Sale en un cuento', 'Su madrastra es malvada', 'Vive con siete enanitos', 'Muerde una manzana envenenada', 'Su piel es blanca como la nieve'], r: 'BLANCANIEVES' },
  { cat: 'PROFESIÓN', pistas: ['Necesita mucho entrenamiento', 'Lleva un traje especial', 'Trabaja sin gravedad', 'Puede vivir en una estación espacial', 'Viaja al espacio'], r: 'ASTRONAUTA' },
  { cat: 'OBJETO', pistas: ['Tiene cuerdas', 'Puede ser eléctrica o española', 'Tiene trastes', 'Se toca con los dedos o con púa', 'Es el instrumento típico del flamenco'], r: 'GUITARRA' },
  { cat: 'COMIDA', pistas: ['Es una sopa', 'Se toma fría', 'Es típica de Andalucía', 'Lleva pepino y pimiento', 'Su ingrediente principal es el tomate'], r: 'GAZPACHO' },
  { cat: 'LUGAR', pistas: ['Está en Asia', 'Está en el Himalaya', 'Hace muchísimo frío', 'Se sube con botellas de oxígeno', 'Es la montaña más alta del mundo'], r: 'EVEREST' },
  { cat: 'ANIMAL', pistas: ['Vive en África o en Asia', 'Es herbívoro', 'Tiene unas orejas enormes', 'Tiene colmillos de marfil', 'Tiene trompa'], r: 'ELEFANTE' },
];

export const CENTRAL: [string, string][] = [
  ['¿Cuál es la capital de Italia?', 'ROMA'],
  ['¿Qué planeta es el más cercano al Sol?', 'MERCURIO'],
  ['¿Cómo se llama el satélite natural de la Tierra?', 'LUNA'],
  ['¿Qué instrumento musical tiene teclas blancas y negras?', 'PIANO'],
  ['¿En qué país está la ciudad de Lisboa?', 'PORTUGAL'],
  ['¿Qué insecto fabrica la miel?', 'ABEJA'],
  ['¿Qué órgano del cuerpo bombea la sangre?', 'CORAZÓN'],
  ['¿Qué océano separa Europa de América?', 'ATLÁNTICO'],
  ['¿Qué día de la semana va después del jueves?', 'VIERNES'],
  ['¿Cuál es el metal precioso de color amarillo?', 'ORO'],
  ['¿Cómo se llama la estrella que nos da luz y calor?', 'SOL'],
  ['¿En qué continente está China?', 'ASIA'],
  ['¿Qué fruta es el ingrediente principal del guacamole?', 'AGUACATE'],
  ['¿Cuál es la capital de Francia?', 'PARÍS'],
  ['¿Qué gas necesitamos respirar para vivir?', 'OXÍGENO'],
  ['¿Cuántos lados tiene un triángulo?', 'TRES'],
  ['¿Qué estación del año empieza en diciembre en España?', 'INVIERNO'],
  ['¿Qué animal es conocido como el rey de la selva?', 'LEÓN'],
  ['¿Qué río pasa por Sevilla?', 'GUADALQUIVIR'],
  ['¿Qué científico propuso la evolución por selección natural?', 'DARWIN'],
  ['¿Qué pintor malagueño pintó el «Guernica»?', 'PICASSO'],
  ['¿Cuál es el idioma oficial de Brasil?', 'PORTUGUÉS'],
  ['¿Qué país europeo tiene forma de bota?', 'ITALIA'],
  ['¿Qué mes tiene 28 días en los años que no son bisiestos?', 'FEBRERO'],
  ['¿Qué animal marino tiene ocho brazos?', 'PULPO'],
  ['¿Cuál es la capital de Alemania?', 'BERLÍN'],
  ['¿Qué aparato se usa para observar las estrellas de cerca?', 'TELESCOPIO'],
  ['¿Qué color sale al mezclar rojo y blanco?', 'ROSA'],
  ['¿Qué planeta es conocido como el planeta rojo?', 'MARTE'],
  ['¿Qué ave es símbolo de la paz?', 'PALOMA'],
  ['¿Cómo se llama el conjunto de huesos del cuerpo?', 'ESQUELETO'],
  ['¿En qué ciudad está la Sagrada Familia?', 'BARCELONA'],
  ['¿Qué escritor creó a Don Quijote?', 'CERVANTES'],
  ['¿Cuál es el animal terrestre más grande?', 'ELEFANTE'],
  ['¿Qué plato valenciano se hace con arroz y azafrán?', 'PAELLA'],
  ['¿Cuál es la capital de Japón?', 'TOKIO'],
  ['¿Cuántos días tiene una semana?', 'SIETE'],
  ['¿Qué instrumento sirve para medir la temperatura?', 'TERMÓMETRO'],
  ['¿Cuál es la moneda oficial de España?', 'EURO'],
  ['¿Qué planeta tiene los anillos más famosos?', 'SATURNO'],
  ['¿Cómo se llama el arco de colores que sale tras la lluvia?', 'ARCOÍRIS'],
  ['¿Qué idioma se habla oficialmente en México?', 'ESPAÑOL'],
];

// ¡DAME LETRA!: [pista de categoría, frase completa]. Refranes, frases hechas y títulos conocidos.
export type DL = [string, string];
export const DAME_LETRA: DL[] = [
  ['Refrán', 'A quien madruga, Dios le ayuda'],
  ['Refrán', 'Más vale tarde que nunca'],
  ['Refrán', 'No hay mal que por bien no venga'],
  ['Refrán', 'Perro ladrador, poco mordedor'],
  ['Refrán', 'En casa de herrero, cuchillo de palo'],
  ['Refrán', 'Ojos que no ven, corazón que no siente'],
  ['Refrán', 'A caballo regalado no le mires el diente'],
  ['Refrán', 'Más vale pájaro en mano que ciento volando'],
  ['Refrán', 'Dime con quién andas y te diré quién eres'],
  ['Refrán', 'Camarón que se duerme se lo lleva la corriente'],
  ['Refrán', 'El que la sigue la consigue'],
  ['Refrán', 'No por mucho madrugar amanece más temprano'],
  ['Refrán', 'Quien mucho abarca poco aprieta'],
  ['Refrán', 'Cría cuervos y te sacarán los ojos'],
  ['Refrán', 'A falta de pan, buenas son tortas'],
  ['Refrán', 'Al mal tiempo, buena cara'],
  ['Refrán', 'Agua que no has de beber, déjala correr'],
  ['Refrán', 'De tal palo, tal astilla'],
  ['Refrán', 'Donde fueres, haz lo que vieres'],
  ['Refrán', 'Zapatero, a tus zapatos'],
  ['Refrán', 'Hablando del rey de Roma, por la puerta asoma'],
  ['Refrán', 'Quien ríe el último ríe mejor'],
  ['Refrán', 'Cada oveja con su pareja'],
  ['Refrán', 'Las apariencias engañan'],
  ['Refrán', 'Ande yo caliente, ríase la gente'],
  ['Frase hecha', 'Estar en las nubes'],
  ['Frase hecha', 'Tirar la casa por la ventana'],
  ['Frase hecha', 'Ponerse las pilas'],
  ['Frase hecha', 'Costar un ojo de la cara'],
  ['Frase hecha', 'Ser pan comido'],
  ['Frase hecha', 'Meter la pata'],
  ['Frase hecha', 'Tomar el pelo'],
  ['Frase hecha', 'Dar gato por liebre'],
  ['Frase hecha', 'Estar como una cabra'],
  ['Frase hecha', 'Echar una mano'],
  ['Frase hecha', 'Buscarle tres pies al gato'],
  ['Frase hecha', 'Hacer la vista gorda'],
  ['Frase hecha', 'Irse por las ramas'],
  ['Frase hecha', 'Ser uña y carne'],
  ['Frase hecha', 'Pedir peras al olmo'],
  ['Película', 'El rey león'],
  ['Película', 'Regreso al futuro'],
  ['Película', 'Lo que el viento se llevó'],
  ['Película', 'La guerra de las galaxias'],
  ['Película', 'Buscando a Nemo'],
  ['Película', 'El mago de Oz'],
  ['Película', 'Solo en casa'],
  ['Película', 'Ocho apellidos vascos'],
  ['Película', 'Mujeres al borde de un ataque de nervios'],
  ['Película', 'El laberinto del fauno'],
  ['Película', 'La bella y la bestia'],
  ['Película', 'Parque Jurásico'],
  ['Canción', 'Cumpleaños feliz'],
  ['Canción', 'Asturias, patria querida'],
  ['Canción', 'Un rayo de sol'],
  ['Canción', 'Clavelitos'],
  ['Canción', 'La bamba'],
  ['Libro', 'Don Quijote de la Mancha'],
  ['Libro', 'Cien años de soledad'],
  ['Libro', 'Platero y yo'],
  ['Libro', 'La vuelta al mundo en ochenta días'],
  ['Libro', 'El principito'],
];

// ¿SÍ O NO?: [pregunta, respuesta correcta (true = sí)]. Datos comprobados.
export type SN = [string, boolean];
export const SI_NO: SN[] = [
  ['¿Es el Teide el pico más alto de España?', true],
  ['¿Es Madrid la capital de Portugal?', false],
  ['¿Tiene una araña ocho patas?', true],
  ['¿Es la ballena azul un pez?', false],
  ['¿Hierve el agua a 100 grados a nivel del mar?', true],
  ['¿Es Júpiter el planeta más grande del sistema solar?', true],
  ['¿Está el desierto del Sáhara en América del Sur?', false],
  ['¿Tiene un año bisiesto 366 días?', true],
  ['¿Escribió Cervantes «Don Quijote de la Mancha»?', true],
  ['¿Pintó Velázquez «Las meninas»?', true],
  ['¿Es el tomate originario de América?', true],
  ['¿Es el pingüino un ave?', true],
  ['¿Pueden volar los avestruces?', false],
  ['¿Es Lisboa la capital de Portugal?', true],
  ['¿Tiene un tablero de ajedrez 64 casillas?', true],
  ['¿Es el Ebro el río más largo de la península ibérica?', false],
  ['¿Es la Luna un planeta?', false],
  ['¿Tiene un hexágono seis lados?', true],
  ['¿Es el corazón un músculo?', true],
  ['¿Es el Everest la montaña más alta del mundo sobre el nivel del mar?', true],
  ['¿Está la Torre Eiffel en Londres?', false],
  ['¿Son los murciélagos mamíferos?', true],
  ['¿Tiene el esqueleto de una persona adulta unos 206 huesos?', true],
  ['¿Es el Pacífico el océano más grande del mundo?', true],
  ['¿Es el delfín un pez?', false],
  ['¿Es Canberra la capital de Australia?', true],
  ['¿Es Sídney la capital de Australia?', false],
  ['¿Es H2O la fórmula química del agua?', true],
  ['¿Tiene una semana ocho días?', false],
  ['¿Está Sevilla en Andalucía?', true],
  ['¿Está Bilbao en Galicia?', false],
  ['¿Es el euro la moneda de España?', true],
  ['¿Están las islas Canarias en el océano Atlántico?', true],
  ['¿Están las islas Baleares en el océano Atlántico?', false],
  ['¿Es el Sol una estrella?', true],
  ['¿Es Marte conocido como el planeta rojo?', true],
  ['¿Gira la Tierra alrededor de la Luna?', false],
  ['¿Es el español el idioma oficial de Brasil?', false],
  ['¿Pone huevos el ornitorrinco?', true],
  ['¿Es la jirafa el animal terrestre más alto?', true],
  ['¿Es el guepardo el animal terrestre más rápido?', true],
  ['¿Es la tortuga un mamífero?', false],
  ['¿Tiene un triángulo cuatro lados?', false],
  ['¿Es el 7 un número primo?', true],
  ['¿Es el 9 un número primo?', false],
  ['¿Tiene una hora 60 minutos?', true],
  ['¿Tiene un siglo mil años?', false],
  ['¿Llegó Colón a América en 1492?', true],
  ['¿Declaró la UNESCO el flamenco Patrimonio Cultural Inmaterial de la Humanidad?', true],
  ['¿Es la paella un plato típico de Valencia?', true],
  ['¿Es el gazpacho una sopa que se toma caliente?', false],
  ['¿Está la Alhambra en Granada?', true],
  ['¿Está la Sagrada Familia en Madrid?', false],
  ['¿Es Gaudí el arquitecto de la Sagrada Familia?', true],
  ['¿Pasa el río Guadalquivir por Sevilla?', true],
  ['¿Pasa el río Tajo por Toledo?', true],
  ['¿Tiene costa la Comunidad de Madrid?', false],
  ['¿Es el mercurio un metal líquido a temperatura ambiente?', true],
  ['¿Está formado el diamante por carbono?', true],
  ['¿Necesitan las plantas luz para hacer la fotosíntesis?', true],
  ['¿Es el oxígeno el gas más abundante del aire?', false],
  ['¿Es la Antártida el continente más frío?', true],
  ['¿Viven osos polares en la Antártida?', false],
  ['¿Tiene un pulpo tres corazones?', true],
  ['¿Es la abeja un insecto?', true],
  ['¿Es la araña un insecto?', false],
  ['¿Tiene el violín cuatro cuerdas?', true],
  ['¿Tiene la guitarra española seis cuerdas?', true],
  ['¿Es el piano un instrumento de viento?', false],
  ['¿Compuso Beethoven la «Novena sinfonía»?', true],
  ['¿Nació Mozart en España?', false],
  ['¿Juega un equipo de fútbol con once jugadores en el campo?', true],
  ['¿Tiene un equipo de baloncesto cinco jugadores en la pista?', true],
  ['¿Fue Barcelona la sede de los Juegos Olímpicos de 1992?', true],
  ['¿Ganó España el Mundial de fútbol de 2010?', true],
  ['¿Es el Mont Blanc más alto que el Teide?', true],
  ['¿Está el río Nilo en África?', true],
  ['¿Está el río Amazonas en Asia?', false],
  ['¿Es Tokio la capital de Japón?', true],
  ['¿Es Nueva York la capital de Estados Unidos?', false],
  ['¿Es Ottawa la capital de Canadá?', true],
  ['¿Es Roma la capital de Italia?', true],
  ['¿Es Berlín la capital de Austria?', false],
  ['¿Es Brasil el país más grande de América del Sur?', true],
  ['¿Está Marruecos en Europa?', false],
  ['¿Tiene España frontera con Francia?', true],
  ['¿Tiene España frontera con Italia?', false],
  ['¿Tiene la bandera de Japón un círculo rojo?', true],
  ['¿Es el kilogramo una unidad de longitud?', false],
  ['¿Tiene un metro 100 centímetros?', true],
  ['¿Es el cero un número par?', true],
  ['¿Son doce las unidades de una docena?', true],
  ['¿Se hace el queso con leche?', true],
  ['¿Se elabora el chocolate a partir del cacao?', true],
  ['¿Es la patata originaria de América?', true],
  ['¿Es Plutón considerado hoy un planeta enano?', true],
  ['¿Es Venus el planeta más cercano al Sol?', false],
  ['¿Tarda la luz del Sol unos ocho minutos en llegar a la Tierra?', true],
  ['¿Fue Neil Armstrong la primera persona en pisar la Luna?', true],
  ['¿Inventó Thomas Edison el teléfono?', false],
  ['¿Escribió Lope de Vega «Don Quijote de la Mancha»?', false],
  ['¿Escribió Federico García Lorca «Bodas de sangre»?', true],
  ['¿Se llama Sancho Panza el escudero de don Quijote?', true],
  ['¿Se llama Rocinante el caballo de don Quijote?', true],
  ['¿Tiene una mariposa cuatro alas?', true],
  ['¿Son mamíferos los tiburones?', false],
  ['¿Tiene el dromedario dos jorobas?', false],
  ['¿Es el Sena el río que pasa por París?', true],
  ['¿Es el Támesis el río que pasa por Roma?', false],
  ['¿Es el rubí una piedra preciosa de color verde?', false],
  ['¿Tiene un cubo seis caras?', true],
  ['¿Tiene un octógono diez lados?', false],
  ['¿Es la sandía una fruta con mucha agua?', true],
  ['¿Es el león un animal herbívoro?', false],
  ['¿Es Barcelona la capital de España?', false],
  ['¿Tiene la Luna luz propia?', false],
  ['¿Es la sal un metal?', false],
  ['¿Es Saturno el planeta más cercano a la Tierra?', false],
  ['¿Se congela el agua a 10 grados sobre cero?', false],
  ['¿Tiene un cuadrado cinco lados?', false],
  ['¿Es el 15 un número primo?', false],
  ['¿Es el caballo un reptil?', false],
  ['¿Es la cebolla una fruta?', false],
  ['¿Es el Cantábrico el mar que baña Málaga?', false],
  ['¿Está Valencia en Castilla y León?', false],
  ['¿Está Santiago de Compostela en Asturias?', false],
  ['¿Es Dublín la capital de Escocia?', false],
  ['¿Es Buenos Aires la capital de Chile?', false],
  ['¿Es el ruso el idioma oficial de Argentina?', false],
  ['¿Tiene un año 13 meses?', false],
  ['¿Tiene febrero 31 días?', false],
  ['¿Es la cobra un mamífero?', false],
  ['¿Es la trompeta un instrumento de cuerda?', false],
  ['¿Pintó Goya «La Gioconda»?', false],
  ['¿Es Neptuno el planeta más cercano al Sol?', false],
  ['¿Es el bronce un elemento químico?', false],
  ['¿Es el hielo más pesado que el mismo volumen de agua líquida?', false],
  ['¿Es el koala un oso?', false],
  ['¿Tiene un insecto ocho patas?', false],
  ['¿Se juega el balonmano con los pies?', false],
  ['¿Es el sushi un plato típico de México?', false],
  ['¿Nació Picasso en Francia?', false],
  ['¿Es Mallorca la isla más grande de Canarias?', false],
  ['¿Es más grande la Luna que la Tierra?', false],
];
